In [11]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Dell\Downloads\archive\marketing_campaign.csv", sep='\t')
print("\nCustomer Personality Analysis Dataset:")
print("\nMissing Values:")
print(df.isnull().sum())
if 'Income' in df.columns:
    df['Income'] = df['Income'].fillna(df['Income'].median())

if 'Dt_Customer' in df.columns:
    df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], format='%d-%m-%Y', errors='coerce')

df = df.dropna(subset=['Dt_Customer'])

for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].str.strip()

df = pd.get_dummies(df, columns=['Education', 'Marital_Status'], drop_first=True)

print("\nCleaned Data Preview:")
print(df.head())

df.to_csv(r"C:\Users\Dell\Downloads\archive\marketing_campaign_cleaned.csv", index=False)

Customer Personality Analysis Dataset:

Missing Values:
ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

Cleaned Data Preview:
     ID  Year_Birth   Income  Kidhome  Teenhome Dt_Customer  Recency  \
0  5524        1957  58138.0        0         0  2012-09-04       58
1  2174        1954  46344.0        1         1  2014-03-08       38
2  4141        1965  71613.0        0         0  2013-08-21       26
3  6182        1984  26646.0        1         0  2014-02-10       26
4  5324        1981  58293.0        1         0  2014-01-19       94

   MntWines  MntFruits  MntMeatProducts  ...  Education_Graduation  \
0       635         88              546  ...                  True
1        11          1                6  ...                  True
2       426         49              127  ...                  True
3        11          4               20  ...                  True
4       173         43              118  ...                 False

   Education_Master  Education_PhD  Marital_Status_Alone  \
0             False          False                 False
1             False          False                 False
2             False          False                 False
3             False          False                 False
4             False           True                 False

   Marital_Status_Divorced  Marital_Status_Married  Marital_Status_Single  \
0                    False                   False                   True
1                    False                   False                   True
2                    False                   False                  False
3                    False                   False                  False
4                    False                    True                  False

   Marital_Status_Together  Marital_Status_Widow  Marital_Status_YOLO
0                    False                 False                False
1                    False                 False                False
2                     True                 False                False
3                     True                 False                False
4                    False                 False                False

[5 rows x 38 columns]